name: Deploy heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "code-server-ipd" #Must be unique in Heroku
          heroku_email: "wynn1275@gmail.com"
          usedocker: true
          docker_build_args: |
            PASSWORD
        env:
          PASSWORD: ${{ secrets.CODE_SERVER_PASSWORD }}
